### ISSUE TITLE
Implement 'not'?

### ISSUE THREAD

**Issue by ahamid** [AnyFetch/logic-query-parser#6]
I'm wondering how difficult it would be to add 'not' as an operator?  I gave it a shot myself but I have to confess I'm very confused as to how the parser works (it doesn't appear to be recursive descent?).

**Comment by Quentin01** [comment]
Sorry for the delay, I have not seen this issue because I no longer maintain the project.

This parser has a weird method to parse the query, not in a classical way. So, to help you, I have done that: https://github.com/AnyFetch/logic-query-parser/tree/not
